In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make("FrozenLake-v1")

In [5]:
action_space = env.action_space.n
state_space = env.observation_space.n

q_table = np.zeros((state_space, action_space))

In [6]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [51]:
EPISODES = 20000
MAX_STEPS = 100

LR = 0.075
DISCOUNT = 0.99

exploration = 1
MAX_EXPLORE = 1
MIN_EXPLORE = 0.01
DECAY = 0.001

In [52]:
rewards_all_episodes=[]

for episode in range(EPISODES):
    
    state = env.reset()
    done = False
    rewards = 0

    for step in range(MAX_STEPS):
        rate = random.uniform(0,1)
        if(rate > exploration):
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()


        new_state, reward, done, info = env.step(action)

        q_table[state,action] *= (1-LR)
        q_table[state,action] += (LR *(reward + (DISCOUNT* np.max(q_table[new_state, :]))))

        state = new_state
        rewards += reward

        if done:
            break
    
    exploration = MIN_EXPLORE + (MAX_EXPLORE - MIN_EXPLORE) * np.exp(-DECAY*episode)
    rewards_all_episodes.append(rewards)

In [53]:
rewards_per_thousand = np.split(np.array(rewards_all_episodes), EPISODES/1000)
count = 1000

print("********Average reward per 1000 episodes********\n")
for r in rewards_per_thousand:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

print("\n\n********Q-Table********\n")
print(q_table)

********Average reward per 1000 episodes********

1000 :  0.05400000000000004
2000 :  0.22600000000000017
3000 :  0.4210000000000003
4000 :  0.5540000000000004
5000 :  0.6110000000000004
6000 :  0.6500000000000005
7000 :  0.6760000000000005
8000 :  0.6580000000000005
9000 :  0.6680000000000005
10000 :  0.6770000000000005
11000 :  0.6480000000000005
12000 :  0.6780000000000005
13000 :  0.6620000000000005
14000 :  0.6870000000000005
15000 :  0.6700000000000005
16000 :  0.6740000000000005
17000 :  0.6950000000000005
18000 :  0.7050000000000005
19000 :  0.6370000000000005
20000 :  0.6580000000000005


********Q-Table********

[[0.27972014 0.2675317  0.26495789 0.26682455]
 [0.1727893  0.16042896 0.17071841 0.24371211]
 [0.22397099 0.19007353 0.1858446  0.2004983 ]
 [0.15657274 0.12464969 0.09665977 0.17301358]
 [0.30990242 0.17036235 0.19826212 0.23434357]
 [0.         0.         0.         0.        ]
 [0.26670228 0.1260102  0.14944354 0.07900691]
 [0.         0.         0.         0.    

In [61]:
x=0
env = gym.make("FrozenLake-v1")
for episode in range(10000):
    state=env.reset()
    done=False
    #time.sleep(1)

    for step in range(MAX_STEPS):        
        #clear_output(wait=True)
        #env.render()
        #time.sleep(0.3)
        # Choose action with highest Q-value for current state       
        # Take new action

        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)

        if done:
            #clear_output(wait=True)
            #env.render()
            if reward == 1:
               print(f'You reached the goal!')
               x+=1
            else:
                print("You fell through a hole!")           

            #time.sleep(3)
            #clear_output(wait=True)
            break
        state = new_state

env.close()
print(x/100)

You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You fell through a hole!
You fell through a hole!
You reached the goal!
You reached the goal!
You reached the goal!
You fell through a hole!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You fell through a hole!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You fell through a hole!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You fell through a hole!
You reached the goal!
You fell through a hole!
You reached the goal!
You fell through a hole!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You reached the goal!
You reac